#!/usr/bin/env php
<?php

require __DIR__.'/ProgressBar.php';

$progress = new ProgressBar(100, 100);

for ($i = 1; $i <= $progress->getTotal(); $i++) {
    $progress->showProgress($i);
    usleep(1000000);
}
